
    create table bookings (
        bookid integer generated by default as identity,
        facid integer not null,
        memid integer not null,
        slots integer not null,
        starttime timestamp(6) not null,
        primary key (bookid)
    );

    create table facilities (
        facid integer generated by default as identity,
        guestcost numeric(38,2) not null,
        initialoutlay numeric(38,2) not null,
        membercost numeric(38,2) not null,
        monthlymaintenance numeric(38,2) not null,
        name varchar(255) not null,
        primary key (facid)
    );

    create table members (
        memid integer generated by default as identity,
        recommendedby integer,
        zipcode integer not null,
        joindate timestamp(6) not null,
        address varchar(255) not null,
        firstname varchar(255) not null,
        surname varchar(255) not null,
        telephone varchar(255) not null,
        primary key (memid)
    );

    alter table if exists bookings 
       add constraint FKmy29jwr9nk4r0c2pq99k90dtm 
       foreign key (facid) 
       references facilities;

    alter table if exists bookings 
       add constraint FK3tboeki504po03rwa0bfju9lk 
       foreign key (memid) 
       references members;

    create table bookings (
        bookid integer generated by default as identity,
        facid integer not null,
        memid integer not null,
        slots integer not null,
        starttime timestamp(6) not null,
        primary key (bookid)
    );

    create table facilities (
        facid integer generated by default as identity,
        guestcost numeric(38,2) not null,
        initialoutlay numeric(38,2) not null,
        membercost numeric(38,2) not null,
        monthlymaintenance numeric(38,2) not null,
        name varchar(255) not null,
        primary key (facid)
    );

    create table members (
        memid integer generated by default as identity,
        recommendedby integer,
        zipcode integer not null,
        joindate timestamp(6) not null,
        address varchar(255) not null,
        firstname varchar(255) not null,
        surname varchar(255) not null,
        telephone varchar(255) not null,
        primary key (memid)
    );

    alter table if exists bookings 
       add constraint FKmy29jwr9nk4r0c2pq99k90dtm 
       foreign key (facid) 
       references facilities;

    alter table if exists bookings 
       add constraint FK3tboeki504po03rwa0bfju9lk 
       foreign key (memid) 
       references members;

    create table bookings (
        bookid integer generated by default as identity,
        facid integer not null,
        memid integer not null,
        slots integer not null,
        starttime timestamp(6) not null,
        primary key (bookid)
    );

    create table facilities (
        facid integer generated by default as identity,
        guestcost numeric(38,2) not null,
        initialoutlay numeric(38,2) not null,
        membercost numeric(38,2) not null,
        monthlymaintenance numeric(38,2) not null,
        name varchar(255) not null,
        primary key (facid)
    );

    create table members (
        memid integer generated by default as identity,
        recommendedby integer,
        zipcode integer not null,
        joindate timestamp(6) not null,
        address varchar(255) not null,
        firstname varchar(255) not null,
        surname varchar(255) not null,
        telephone varchar(255) not null,
        primary key (memid)
    );

    alter table if exists bookings 
       add constraint FKmy29jwr9nk4r0c2pq99k90dtm 
       foreign key (facid) 
       references facilities;

    alter table if exists bookings 
       add constraint FK3tboeki504po03rwa0bfju9lk 
       foreign key (memid) 
       references members;

    create table bookings (
        bookid integer generated by default as identity,
        facid integer not null,
        memid integer not null,
        slots integer not null,
        starttime timestamp(6) not null,
        primary key (bookid)
    );

    create table facilities (
        facid integer generated by default as identity,
        guestcost numeric(38,2) not null,
        initialoutlay numeric(38,2) not null,
        membercost numeric(38,2) not null,
        monthlymaintenance numeric(38,2) not null,
        name varchar(255) not null,
        primary key (facid)
    );

    create table members (
        memid integer generated by default as identity,
        recommendedby integer,
        zipcode integer not null,
        joindate timestamp(6) not null,
        address varchar(255) not null,
        firstname varchar(255) not null,
        surname varchar(255) not null,
        telephone varchar(255) not null,
        primary key (memid)
    );

    alter table if exists bookings 
       add constraint FKmy29jwr9nk4r0c2pq99k90dtm 
       foreign key (facid) 
       references facilities;

    alter table if exists bookings 
       add constraint FK3tboeki504po03rwa0bfju9lk 
       foreign key (memid) 
       references members;

    create table bookings (
        bookid integer generated by default as identity,
        facid integer not null,
        memid integer not null,
        slots integer not null,
        starttime timestamp(6) not null,
        primary key (bookid)
    );

    create table facilities (
        facid integer generated by default as identity,
        guestcost numeric(38,2) not null,
        initialoutlay numeric(38,2) not null,
        membercost numeric(38,2) not null,
        monthlymaintenance numeric(38,2) not null,
        name varchar(255) not null,
        primary key (facid)
    );

    create table members (
        memid integer generated by default as identity,
        recommendedby integer,
        zipcode integer not null,
        joindate timestamp(6) not null,
        address varchar(255) not null,
        firstname varchar(255) not null,
        surname varchar(255) not null,
        telephone varchar(255) not null,
        primary key (memid)
    );

    alter table if exists bookings 
       add constraint FKmy29jwr9nk4r0c2pq99k90dtm 
       foreign key (facid) 
       references facilities;

    alter table if exists bookings 
       add constraint FK3tboeki504po03rwa0bfju9lk 
       foreign key (memid) 
       references members;

    create table bookings (
        bookid integer generated by default as identity,
        facid integer not null,
        memid integer not null,
        slots integer not null,
        starttime timestamp(6) not null,
        primary key (bookid)
    );

    create table facilities (
        facid integer generated by default as identity,
        guestcost numeric(38,2) not null,
        initialoutlay numeric(38,2) not null,
        membercost numeric(38,2) not null,
        monthlymaintenance numeric(38,2) not null,
        name varchar(255) not null,
        primary key (facid)
    );

    create table members (
        memid integer generated by default as identity,
        recommendedby integer,
        zipcode integer not null,
        joindate timestamp(6) not null,
        address varchar(255) not null,
        firstname varchar(255) not null,
        surname varchar(255) not null,
        telephone varchar(255) not null,
        primary key (memid)
    );

    alter table if exists bookings 
       add constraint FKmy29jwr9nk4r0c2pq99k90dtm 
       foreign key (facid) 
       references facilities;

    alter table if exists bookings 
       add constraint FK3tboeki504po03rwa0bfju9lk 
       foreign key (memid) 
       references members;

    create table bookings (
        bookid integer generated by default as identity,
        facid integer not null,
        memid integer not null,
        slots integer not null,
        starttime timestamp(6) not null,
        primary key (bookid)
    );

    create table facilities (
        facid integer generated by default as identity,
        guestcost numeric(38,2) not null,
        initialoutlay numeric(38,2) not null,
        membercost numeric(38,2) not null,
        monthlymaintenance numeric(38,2) not null,
        name varchar(255) not null,
        primary key (facid)
    );

    create table members (
        memid integer generated by default as identity,
        recommendedby integer,
        zipcode integer not null,
        joindate timestamp(6) not null,
        address varchar(255) not null,
        firstname varchar(255) not null,
        surname varchar(255) not null,
        telephone varchar(255) not null,
        primary key (memid)
    );

    alter table if exists bookings 
       add constraint FKmy29jwr9nk4r0c2pq99k90dtm 
       foreign key (facid) 
       references facilities;

    alter table if exists bookings 
       add constraint FK3tboeki504po03rwa0bfju9lk 
       foreign key (memid) 
       references members;
